# -*- coding: utf-8 -*-
from PyQt5 import QtCore

class STM32Controle(QtCore.QObject):
    updated = QtCore.pyqtSignal(dict)  # {zone_idx: [id1, ...]} OR backend forms
    def start(self): ...
    def stop(self): ...
    def reset(self): ...
    def set_num_mice(self, n: int): ...
